name: "Setup Flutter env"
description: "Setup Flutter and dependencies"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/parse-flutter-version
      id: fvmrc
    - uses: subosito/flutter-action@395322a6cded4e9ed503aebd4cc1965625f8e59a # v2.20.0
      with:
        flutter-version: ${{ steps.fvmrc.outputs.flutter-version }}
        channel: stable
        cache: true
        cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
        cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
        pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
        pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
    - name: Install packages
      run: flutter pub get --no-example
      shell: bash
    - name: Run build_runner
      run: dart run build_runner build
      shell: bash
