name: Build and test
on:
  pull_request:

env:
  API_KEY: api_key
  SHARED_SECRET: shared_secret

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: state_app
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.22.3'
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - name: Install packages
        run: flutter pub get
      - name: Prepare env
        run: |
          echo "API_KEY=${{ env.API_KEY }}" >> .env
          echo "SHARED_SECRET=${{ env.SHARED_SECRET }}" >> .env
      - name: Run build_runner
        run: dart run build_runner build
      - name: Linter
        run: flutter analyze
      - name: Run tests
        run: flutter test
