name: Build and test
on:
  pull_request:

env:
  API_KEY: api_key
  SHARED_SECRET: shared_secret

concurrency:
  group: build-${{ github.head_ref || 'develop' }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare env
        run: |
          echo "API_KEY=${{ env.API_KEY }}" >> .env
          echo "SHARED_SECRET=${{ env.SHARED_SECRET }}" >> .env
      - name: Setup Flutter env
        uses: ./.github/actions/setup-flutter-project

      - name: Build binary
        run: |
          flutter build ipa --no-codesign

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Prepare env
        run: |
          echo "API_KEY=${{ env.API_KEY }}" >> .env
          echo "SHARED_SECRET=${{ env.SHARED_SECRET }}" >> .env
      - name: Setup Flutter env
        uses: ./.github/actions/setup-flutter-project
      - name: Build binary
        run: |
          flutter build appbundle --debug # --release is better

  test:
    # Align the environment for taking screenshots with the development environment.
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare env
        run: |
          echo "API_KEY=${{ env.API_KEY }}" >> .env
          echo "SHARED_SECRET=${{ env.SHARED_SECRET }}" >> .env
      - name: Setup Flutter env
        uses: ./.github/actions/setup-flutter-project
      - name: Linter
        run: flutter analyze
      - name: Run tests
        run: flutter test --machine > report.json
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: flutter test
          path: report.json
          reporter: flutter-json
          fail-on-error: false
